# Generated by Django 2.1.5 on 2019-04-15 10:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='GoalStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status_name', models.CharField(max_length=200)),
            ],
            options={
                'verbose_name_plural': 'Goal Status',
            },
        ),
        migrations.CreateModel(
            name='ScrumProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project_count', models.IntegerField(default=None)),
            ],
            options={
                'verbose_name_plural': 'Scrum Project',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ScrumProjectRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(default=None, max_length=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remiljscrumy.ScrumProject')),
            ],
            options={
                'verbose_name_plural': 'Scrum Project Role',
                'ordering': ['project'],
            },
        ),
        migrations.CreateModel(
            name='ScrumUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=50)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Scrum User',
                'ordering': ['nickname'],
            },
        ),
        migrations.CreateModel(
            name='ScrumyGoals',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visible', models.BooleanField(default=True)),
                ('moveable', models.BooleanField(default=True)),
                ('goal_name', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('moved_by', models.CharField(max_length=200)),
                ('owner', models.CharField(max_length=200)),
                ('goal_status', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='remiljscrumy.GoalStatus')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remiljscrumy.ScrumProject')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remiljscrumy.ScrumProjectRole')),
            ],
            options={
                'verbose_name_plural': 'Scrumy Goals',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='ScrumyHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('moved_by', models.CharField(max_length=200)),
                ('created_by', models.CharField(max_length=200)),
                ('moved_from', models.CharField(max_length=200)),
                ('moved_to', models.CharField(max_length=200)),
                ('time_of_action', models.DateTimeField()),
                ('goal', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remiljscrumy.ScrumyGoals')),
            ],
            options={
                'verbose_name_plural': 'Scrumy History',
            },
        ),
        migrations.AddField(
            model_name='scrumprojectrole',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='remiljscrumy.ScrumUser'),
        ),
    ]
