# Generated by Django 2.1.5 on 2019-04-15 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0003_auto_20190415_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumprojectrole',
            name='role',
        ),
        migrations.AddField(
            model_name='scrumprojectrole',
            name='roles',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
