# Generated by Django 2.1.5 on 2019-04-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0004_auto_20190415_1209'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumprojectrole',
            name='roles',
        ),
        migrations.AddField(
            model_name='scrumprojectrole',
            name='role',
            field=models.CharField(default=None, max_length=50),
        ),
    ]
