# Generated by Django 2.1.5 on 2019-04-15 11:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0005_auto_20190415_1214'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrumproject',
            name='project_count',
            field=models.IntegerField(default=0),
        ),
    ]
