# Generated by Django 2.1.5 on 2019-04-15 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0006_auto_20190415_1217'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrumygoals',
            name='created_by',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='moved_by',
        ),
        migrations.RemoveField(
            model_name='scrumygoals',
            name='owner',
        ),
        migrations.AddField(
            model_name='scrumygoals',
            name='goal_project_id',
            field=models.IntegerField(default=0),
        ),
    ]
