# Generated by Django 2.2 on 2019-04-24 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('remiljscrumy', '0009_auto_20190424_1459'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='email',
            field=models.TextField(max_length=50, null=True),
        ),
    ]
